### PR TITLE
Change total profit to net profit

### PR DESCRIPTION
**Pull request by psolyca**
When trading, the real profit is the one taking into account taxes.
Thus, this add sell tax in Station to Station trading.
Total profit become Gross margin and Net Profit is introduced.

ToDo :

 - [x] Add sales tax for station to station trading
 - [x] Add sales tax for region to region trading
 - [x] Add sales tax for station trading
 - [x] Keep sales tax for reuse

### CODE REVIEW

**Comment by awhipp** [comment]
Happy to accept this PR, but you need to run the production build so that the code is built and deployed to **dist/**

Once it is in there I can QA in dev and bring it into master.

**Comment by psolyca** [comment]
Done.

**Comment by psolyca** [comment]
This PR is only for station to station trade.
I need to add it for other trading.

**Comment by awhipp** [comment]
Have you tested this? 
* The Sales Tax does not allow decimals (see attached).
* It also breaks the station list. It should be placed within the form. 
* The search is also broken

You can find your preview branch URL here: https://deploy-preview-112--evetrade.netlify.com/

Capture

Capture2

**Comment by psolyca** [comment]
Should be fixed.
I place sale taxes input lower in the view.

**Comment by awhipp** [comment]
Thanks I'll test over the next few days and get back to you. 

If all looks good and it gets merged we can test at dev.evetrade.space for a few more days and then we can get it into master by next week.

**Comment by psolyca** [comment]
I have added a last commit which let users see taxes in search results.
It was not attended but I have seen this as usefull if one want to check.

**Comment by psolyca** [comment]
I have an other branch which introduce brokers fees on station trading to complet net profit but did not propose a PR yet cause this PR #112 have to be merge before.

Do you mind if I add the commit here or wait to create an other PR ?

**Comment by awhipp** [comment]
Feel free to add it. I typically don't have time during the work week to review PRs so you have time.

**Comment by awhipp** [comment]
@psolyca Looks good on https://deploy-preview-112--evetrade.netlify.com/

Merging into dev for testing.

Before we merge it into master we should try to center the tax input field.

**Pull request merged**
