### PR TITLE
Fix/updated sources

### LINKED ISSUE #129: List of stations are not up to date
**Describe the bug**
Some stations do not exist anymore or their name change since the creation of the website.
I compare against official DB usi https://esi.evetech.net/ui/#/
For example :
https://github.com/awhipp/evetrade/blob/599005c18b3148cea32d25f9b3fa258da142b717/js/station_ids.js#L3-L5
and
https://github.com/awhipp/evetrade/blob/599005c18b3148cea32d25f9b3fa258da142b717/js/station_ids.js#L8-L10
Do not exist anymore with  https://esi.evetech.net/ui/#/Universe/get_universe_stations_station_id: 
```
  "error": "Station not found"
```
But have a different name (why not anymore a station !) with https://esi.evetech.net/ui/#/Universe/post_universe_names
```
"category": "station",
"id": 60014862,
"name": "0-G8NO VIII - Moon 1 - CSQY stronghold "
```
and
```
"category": "station",
"id": 60014885,
"name": "0-W778 VII - Moon 2 - Ranger Regiment's Outpost"
```

**To Reproduce**
...

**Expected behavior**
Up to date DB

### PR DESCRIPTION
**Pull request by psolyca**
Should fix #129.

May speed up loading !?

### CODE REVIEW

**Comment by awhipp** [comment]
My only concern is what happens if this end point isn't available? Eve's api is backed by a big company. Not sure who owns this.

**Comment by psolyca** [comment]
I thought of this also.
I think I can get information directly from ESI but I have to check if I need computation.

**Comment by awhipp** [comment]
Pretty sure you can. I investigated it before but it involves multiple round trip calls. I believe one to get station id's and then multiple to get names.

**Comment by psolyca** [comment]
I just have a look.
There is no way to get all IDs of stations from one request.
We can get all IDs of systems and regions then we had to look for each station by its ID.

**Comment by psolyca** [comment]
@awhipp 
Here is a proposition for keeping resources files along the Eve Trade repo.

I created a repo which you have to fork : https://github.com/psolyca/evetrade_resources
On this repo, there is multiple scripts + a Travis CI file which trigger a build and deploy created files to the releases page.

You need to create a Personal Acces Token (PAT) on Github: https://github.com/settings/tokens with repo checked.
Keep this token somewhere
Go to https://travis-ci.org/awhipp/evetrade_resources/settings (after creating and syncing your repo)
Create an environment variable, named it GH_TOKEN and the value is your PAT
Create a Cron job on master, every month and Do not run if 24h...
Wait for the first cron job to launch.
You should have 2 files in releases page accessible with the "latest release" link (usefull to avoid tag search) 

Hope this will work (it is with my repo).

I will then use these to finish this PR.

**Comment by awhipp** [comment]
What a great idea! Good work. You can find it here and I've linked to the build status as well.

https://github.com/awhipp/evetrade_resources

**Comment by timegrinder** [comment]
Fantastic work! I've been doing this manually using the DB downloads for my own purposes, glad to see the name updates being put into EveTrade.

**Comment by psolyca** [comment]
Aaarg guys I am sorry to tell you that this does not work...
Files in the release page of Github are in reality in a Amazon S3 server which does not handle Json files but only binary files. Thus, grabbing json is a pain.
A possility could be to push from Travis to Github but there is a password issue.
Last and maybe the better is to push the json files directly to Netlify. Apparently it is possible but I did not search more. Will try to investigate these next day.
@awhipp could I mail you directly if I need?
BTW, I have opened a Gitter chat if you had the invitation. It will be easier and will not pollute this PR.

**Comment by awhipp** [comment]
You can mail me directly if you want.

That said I'm going to try to push directly to the repo or to a cdn with the latest files instead of using releases. I'll test it out and let you know.

**Comment by psolyca** [comment]
I really don't know how Netlify work. Do you need a server to deploy Netlify build or everything is served on Netlify server?
I have a other idea to push files directly on Github.
BTW, if you have your own server, it could be possible to upload to it. Create environment variables and use them in .travis.yml file. You can encode them with the Travis CLI.

**Comment by psolyca** [comment]
@awhipp I do not have your email ^^;

You can fetch my repo evetrade_resources.

Read the instruction in the README and you should have the correct files on the repo. I made a complete test with my repo and it is functionning.

Check if your Travis CI build is not looping... I had the problem but I made a check to avoid this.

**Comment by awhipp** [comment]
@psolyca 
Hey, I set everything up. See the logs here: https://travis-ci.org/awhipp/evetrade_resources
Seems like its expecting a password for the SSH key thats generated but we do not set one.

**Comment by psolyca** [comment]
@awhipp 
When using `travis encrypt-file github_deploy_key` does the Travis CI setting https://travis-ci.org/awhipp/evetrade_resources/settings have the 2 variables named `encrypted_xxxxxxxxxxxx_key` 
 and `encrypted_xxxxxxxxxxxx_iv` ? If yes, does their name have xxxxxxxxxxxx or a 12 digits ?
If you have 12 digits, you have to update (mine had 12 digits) https://github.com/awhipp/evetrade_resources/blob/4ba1262645942136923c78fb53ac1097c8176ea0/.travis.yml#L15-L16 
That is the only think I can see right now... or your are using Travis CLI under Windows which do no work.

**Comment by awhipp** [comment]
@psolyca Happy New Year.

I confirmed that the variables are set properly. I am using Ubuntu 18.x

I'll start fresh and try it again today. I was working on this around family for the holidays so it is entirely likely I added or missed a step somewhere along the way.

**Comment by awhipp** [comment]
@psolyca No success. Repeated the steps and unfortunately there was no change. Still does not recognize the keys.

It hangs when trying to push to the repo and does not seem to see the identity. Were you able to get it to work in your own repo? We can just link to yours if you do not delete them. 😄 

Logs: https://travis-ci.org/awhipp/evetrade_resources

**Comment by psolyca** [comment]
I clear all information to anonymize the main repo.
So I have to redo it has I made it on a test repo.
Tomorrow ^^

Weird, on your build I only have one variable :

`
Setting environment variables from .travis.yml
$ export GH_USER_EMAIL=[secure]
`
Not the GH_USER_NAME and that is why your build failed this time.

**Comment by awhipp** [comment]
Strange guess I did not encode it properly. Good catch. Unfortunately the original issue still occurs.

New logs are up - https://travis-ci.org/awhipp/evetrade_resources

**Comment by psolyca** [comment]
Could you had a .git to the GH_REPO variable ?
Line 170 should be : 
```
 export GH_REPO=awhipp/evetrade_resources.git
```

**Comment by awhipp** [comment]
No success.

**Comment by psolyca** [comment]
Ok :(
Will see tomorrow, to late.

**Comment by psolyca** [comment]
Ok I manage to build ^^

The only difference with your build log is line 164-165 of mine (https://travis-ci.org/psolyca/evetrade_resources) :
```
$ export encrypted_46d5c4daa580_key=[secure]
$ export encrypted_46d5c4daa580_iv=[secure]
```

Your lines (168-169 in https://travis-ci.org/awhipp/evetrade_resources) are :
```
$ export encrypted_xxxxxxxxxxxx_key=[secure]
$ export encrypted_xxxxxxxxxxxx_iv=[secure]
```
Check your https://travis-ci.org/awhipp/evetrade_resources/settings
for these variables name !! I do not know why you have xxxxxxxxxx !!

You also should have 2 builds, one which build and one which say that the files are already up to date.

**Comment by awhipp** [comment]
Ah based on the images I thought **encrypted_xxxxxxxxxxxx_key** was they key and the value provided was the secure value.

**Comment by awhipp** [comment]
@psolyca FINALLY. That was it. I was just misunderstanding the key/values. 

Resources have been deployed successfully: https://github.com/awhipp/evetrade_resources/tree/master/resources

**Comment by psolyca** [comment]
@awhipp Great.
This PR could be merged and closed ^^

**Comment by awhipp** [comment]
Looks great! Good work!

**Pull request merged**
