### PR TITLE
Release 6.5

### PR DESCRIPTION
**Pull request by awhipp**

### CODE REVIEW

**Comment by awhipp** [comment]
@psolyca I've cut release 6.5 and added you as a collaborator. I've also reviewed and tested for a bit and have found no issues other than the usual browser lag if I select too many regions.

Feel free to approve this PR when you are happy with it and I will merge it in.

**Comment by psolyca** [comment]
I have a little UI bug in station trading, the suggested stations are not shown anywhere but taken into account for the search.

**Comment by psolyca** [comment]
As I can not directly push commits to dev, I made the PR #161 to finalize this one.
I have tested nearly all features of this dev branch and every thing seems functional.

**Comment by awhipp** [comment]
Good catch. I must have overlooked that. Merged your change into dev and it looks to be resolved. If that is all you caught, feel free to approve this PR and I will merge it into master.

**Pull request merged**
