### PR TITLE
Fix station trading calculation

### PR DESCRIPTION
**Pull request by psolyca**
This will fix issue #113

### CODE REVIEW

**Comment by awhipp** [comment]
Station Trading is not working. Try a search with Volume > 100 and Margins between 0-100%.

It should practically return everything on the market. It instead returns nothing.

Web preview link: https://deploy-preview-114--evetrade.netlify.com/

Capture3

**Comment by psolyca** [comment]
Maybe I misunderstanding the function of the station trading system ?

Is this for instant trading or to help placing orders on goods ?

**Comment by awhipp** [comment]
It's not for instant trading. You will never find a sell order that is less than a buy order at the same station. It's for placing buy orders at the same station you are selling them at. 

Either way the PR broke functionality and no results are returned when there should be.

Try the same query on the live server and you'll see the difference.

**Comment by psolyca** [comment]
Haha, I misunderstand the function ^^;
Your last comment confirm what I thought about placing orders.
So I can close this PR and delete my branch.

**Pull request closed without merging**
