### PR TITLE
Fix setDefaultVal function

### PR DESCRIPTION
**Pull request by psolyca**
The function was returning a string whereas a number is required.

Should fix https://github.com/awhipp/evetrade/issues/118

### CODE REVIEW

**Comment by psolyca** [comment]
@awhipp should I merge all my other PRs in this one also ?

**Comment by awhipp** [comment]
@psolyca Just merged into dev. I am going to try to fix the build so you do not have conflicting dist files everytime.

**Comment by awhipp** [comment]
@psolyca Merge dev into your branch and you no longer need to build jekyll before committing. The server will do it for you and deploy to dist automatically.

That said, I did notice a bug when testing  your new code. The Net Profit and Gross Margin columns are mixed up. Net Profit should be greater than Gross Margin since Net Profit is Total - Cost of Goods.

See EVETrade example: https://imgur.com/a/uM2WlkO
See balance sheet example: https://imgur.com/a/HVDT7iH

**Comment by psolyca** [comment]
Ooooh thanks, it was really a pain to play with Jekyll to serve for dev then build for prod ^^

Trading is far from what I understand clearly :p
After rereading some websites and https://en.wikipedia.org/wiki/Net_income, in our simplified view :
Gross Margin = Net sales - Net costs
Net Income (Net Profit) = Gross Margin - Taxes

I have used "Net Profit" for "Net Income".  It is just that I did not mention "Net Sales" maybe that is why you though I was talking about it when I have used "Net Profit".
So I should change / add columns as the following :

Sell Order | From | Quantity | Buy Price | Net Costs | Take To | Sell Price | Net Sales | Gross Margin | Sell Taxes | Net Profit | Jumps | Profit per Jump | R.O.I. | Total Volume (m3) 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
 | | | | | | | | | | | | | | 

Net Costs = Quantity * Buy Price
Net Sales = Quantity * Sell Price
Gross Margin = Net Sales - Net Costs
Net Profit = Gross Margin - Sell Taxes

Does that work for you ?

**Comment by awhipp** [comment]
Honestly that's too many columns. It's not a good user experience as you add that many columns. It should really just be net profit. The others don't matter.

**Comment by psolyca** [comment]
Ok so I change to :

Sell Order | From | Quantity | Buy Price | Net Costs | Take To | Sell Price | Net Profit | Jumps | Profit per Jump | R.O.I. | Total Volume (m3) 
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 | | | | | | | | | | | |

Removed "Net Sales", "Gross Margin" and "Sell Taxes".
"Net Costs" could also be removed as important columns are "Quantity", "Buy Price" and "Sell Price".
Or is it possible to hide by default some columns ? For people who wants more information (like me :p )

**Comment by awhipp** [comment]
Yeah you can hide those by default and use the drop down to add them in. That'd be a good compromise. If you are on a Mac air or a smaller laptop the table begins to get cut off. 10-12 columns seems to be the right number before it starts to be too many.

**Comment by psolyca** [comment]
Ok, will make another PR ^^

**Comment by awhipp** [comment]
Thanks. I know a lot of users have small monitors and it became an issue when I started adding columns early on.

**Pull request merged**
